// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'can not show this secret',
    appId: '1:492706844423:web:b880812118ecfa5e59bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    authDomain: 'class-sync-eb06a.firebaseapp.com',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    measurementId: 'G-H1EWKNN129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'can not show this secret',
    appId: '1:492706844423:android:093d5c3c129400b859bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'can not show this secret',
    appId: '1:492706844423:ios:94b23a6e07e934bd59bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    androidClientId: '492706844423-2gea5e4e8fjhgdqiqrpievhp76cbtl5o.apps.googleusercontent.com',
    iosClientId: '492706844423-ivbu39d4679eoivdv6jsh4vph9nm03s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.classSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'can not show this secret',
    appId: '1:492706844423:ios:94b23a6e07e934bd59bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    androidClientId: '492706844423-2gea5e4e8fjhgdqiqrpievhp76cbtl5o.apps.googleusercontent.com',
    iosClientId: '492706844423-ivbu39d4679eoivdv6jsh4vph9nm03s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.classSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'can not show this secret-g',
    appId: '1:492706844423:web:9fddafd417ce7ebe59bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    authDomain: 'class-sync-eb06a.firebaseapp.com',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    measurementId: 'G-6Z9BZQPL2W',
  );

}
