// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgXymrtyxdjgaxuvLHoi6fysVWg4DkQQ',
    appId: '1:492706844423:web:447d1ea57aa30ce259bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    authDomain: 'class-sync-eb06a.firebaseapp.com',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    measurementId: 'G-CG2PP2WZ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfrlx6XT2HzPGz_SQJXgCSOeFmLYnucg',
    appId: '1:492706844423:android:20afc81746196a8859bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCne6LI4Ig_UloNuoNPrEnMZ9Wdk9E0OcA',
    appId: '1:492706844423:ios:ef0f4b58677b539559bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    androidClientId: '492706844423-2gea5e4e8fjhgdqiqrpievhp76cbtl5o.apps.googleusercontent.com',
    iosClientId: '492706844423-5dnv7mtv2oq06kkc745tkokdrvn0f41h.apps.googleusercontent.com',
    iosBundleId: 'com.classsyncadmin.classSyncAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCne6LI4Ig_UloNuoNPrEnMZ9Wdk9E0OcA',
    appId: '1:492706844423:ios:ef0f4b58677b539559bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    androidClientId: '492706844423-2gea5e4e8fjhgdqiqrpievhp76cbtl5o.apps.googleusercontent.com',
    iosClientId: '492706844423-5dnv7mtv2oq06kkc745tkokdrvn0f41h.apps.googleusercontent.com',
    iosBundleId: 'com.classsyncadmin.classSyncAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDgXymrtyxdjgaxuvLHoi6fysVWg4DkQQ',
    appId: '1:492706844423:web:7746af370b15e1e159bfa2',
    messagingSenderId: '492706844423',
    projectId: 'class-sync-eb06a',
    authDomain: 'class-sync-eb06a.firebaseapp.com',
    storageBucket: 'class-sync-eb06a.firebasestorage.app',
    measurementId: 'G-5H7KCHR1L6',
  );

}